name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.18.0]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.OTHER_GITHUB_TOKEN }}
      run: npx semantic-release